### ISSUE TITLE
pip install hamradio not working

### ISSUE THREAD

**Issue by gmacie** [schlatterbeck/wsjtx-srv#1]
Any Help would be appreciated with this !

C:\gmpywsjtx>python gm_wsjtx_try.py

Traceback (most recent call last):
  File "gm_wsjtx_try.py", line 12, in <module>
    from hamradio.adif     import ADIF
ModuleNotFoundError: No module named 'hamradio'

C:\gmpywsjtx>pip install hamradio
Collecting hamradio
  Using cached hamradio-0.3.tar.gz (150 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in hamradio setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'<rsclib>'"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by schlatterbeck** [comment]
Thanks for the bug-report, seems I got the install_requires settings syntactically wrong.
I've uploaded a new release of hamradio, can you try re-install with

pip install -U hamradio

The -U (upgrade) option will download the latest version.

**Comment by schlatterbeck** [comment]
Re-opening until we have some feedback.

**Comment by gmacie** [comment]
That took care of it. Thanks

Gordy N4LR

**Comment by schlatterbeck** [comment]
Thanks for the quick feedback, closing
